# Generated by Django 3.2.13 on 2022-11-19 12:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('sido', models.CharField(max_length=20)),
                ('sigungu', models.CharField(max_length=30)),
                ('roadname', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('opening_hour', models.CharField(max_length=40)),
                ('menu', froala_editor.fields.FroalaField()),
                ('parking', models.CharField(max_length=20)),
                ('dayoff', models.CharField(max_length=20)),
                ('cafeType', models.CharField(choices=[('분위기가 좋은', '분위기가 좋은'), ('디저트가 맛있는', '디저트가 맛있는'), ('커피가 맛있는', '커피가 맛있는'), ('작업하기 좋은', '작업하기 좋은'), ('커피가 저렴한', '커피가 저렴한'), ('이색적인', '이색적인')], max_length=20, null=True)),
                ('image1', imagekit.models.fields.ProcessedImageField(upload_to='images/cafe')),
                ('image2', imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='images/cafe')),
                ('image3', imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='images/cafe')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('hits', models.PositiveBigIntegerField(default=0, verbose_name='조회수')),
                ('bookmark_users', models.ManyToManyField(related_name='bookmark_articles', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', froala_editor.fields.FroalaField()),
                ('rate', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.article')),
                ('like_users', models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('like_users', models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='cafes.comment')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
