# Generated by Django 3.2.13 on 2022-11-21 19:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_alter_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='images/cafe'),
        ),
    ]
