# Generated by Django 3.2.13 on 2022-11-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_article_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='menuStripTag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
