# Generated by Django 3.2.13 on 2022-11-02 02:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='typeOfFood',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('한식', '한식'), ('일식', '일식'), ('중식', '중식'), ('양식', '양식'), ('분식', '분식'), ('치킨', '치킨'), ('아시안', '아시안'), ('패스트푸드', '패스트푸드'), ('디저트/카페', '디저트/카페'), ('기타', '기타')], default=None, max_length=37),
            preserve_default=False,
        ),
    ]
