# Generated by Django 3.2.13 on 2022-11-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_typeoffood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='typeOfFood',
        ),
        migrations.AddField(
            model_name='article',
            name='foodType',
            field=models.CharField(choices=[('한식', '한식'), ('일식', '일식'), ('중식', '중식'), ('양식', '양식'), ('분식', '분식'), ('치킨', '치킨'), ('아시안', '아시안'), ('패스트푸드', '패스트푸드'), ('디저트/카페', '디저트/카페'), ('기타', '기타')], max_length=7, null=True),
        ),
    ]
