# Generated by Django 3.2.13 on 2022-11-03 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20221102_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='grade',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
