# Generated by Django 3.2.13 on 2022-11-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_grade'),
        ('articles', '0004_alter_article_image'),
    ]

    operations = [
    ]
