# Generated by Django 3.2.13 on 2022-11-03 05:38

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_merge_20221103_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=10, upload_to='images/'),
            preserve_default=False,
        ),
    ]
