# Generated by Django 3.2.13 on 2022-11-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_comment_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(default='서울시 용산구 남산공원길 105', max_length=150),
        ),
    ]
