# Generated by Django 3.2.13 on 2022-11-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='address',
        ),
    ]
