# Generated by Django 3.2.13 on 2022-11-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='roadname',
            field=models.CharField(default='판교역로', max_length=30),
            preserve_default=False,
        ),
    ]
