# Generated by Django 3.2.13 on 2022-10-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customletters',
            name='garbage',
            field=models.BooleanField(default=False),
        ),
    ]
